"""initial schema

Revision ID: 2137c3e61bfd
Revises: 
Create Date: 2026-09-25 19:44:36.212094
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.models.types


revision: str = '2137c3e61bfd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('last_used_at', app.models.types.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'API_CLIENT', 'SYSTEM', name='actortype', native_enum=False, length=24), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('actor_name', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cameras',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('camera_type', sa.Enum('FIXED', 'PTZ', 'ANPR', 'DOME', 'BULLET', 'THERMAL', name='cameratype', native_enum=False, length=24), nullable=False),
    sa.Column('source_protocol', sa.Enum('RTSP', 'ONVIF', 'HLS', 'VENDOR_API', name='sourceprotocol', native_enum=False, length=24), nullable=False),
    sa.Column('stream_endpoint', sa.String(length=512), nullable=False),
    sa.Column('stream_username', sa.String(length=128), nullable=True),
    sa.Column('stream_secret_enc', sa.Text(), nullable=True),
    sa.Column('resolved_stream_uri', sa.String(length=512), nullable=True),
    sa.Column('gateway_path', sa.String(length=64), nullable=True),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('resolution', sa.String(length=16), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('recording_enabled', sa.Boolean(), nullable=False),
    sa.Column('storage_tier', sa.String(length=16), nullable=True),
    sa.Column('storage_location', sa.String(length=255), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('health_mode', sa.Enum('PROBE', 'HEARTBEAT', name='healthmode', native_enum=False, length=24), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'DEGRADED', 'OFFLINE', 'UNKNOWN', name='camerastatus', native_enum=False, length=24), nullable=False),
    sa.Column('status_reason', sa.String(length=255), nullable=True),
    sa.Column('status_changed_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('last_heartbeat_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('health_metrics', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('onboarding_source', sa.Enum('MANUAL', 'API', 'DISCOVERY', 'SEED', name='onboardingsource', native_enum=False, length=24), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cameras_dept_zone', 'cameras', ['department_id', 'zone'], unique=False)
    op.create_index('ix_cameras_geo', 'cameras', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_cameras_protocol', 'cameras', ['source_protocol'], unique=False)
    op.create_index('ix_cameras_status', 'cameras', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='role', native_enum=False, length=24), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('last_login_at', app.models.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('detection_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_uid', sa.String(length=64), nullable=False),
    sa.Column('camera_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.Enum('ANPR', 'VEHICLE_DETECTION', 'PERSON_DETECTION', 'FACE_RECOGNITION', 'OBJECT_DETECTION', name='eventtype', native_enum=False, length=24), nullable=False),
    sa.Column('detected_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('received_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=True),
    sa.Column('identifier_normalized', sa.String(length=64), nullable=True),
    sa.Column('vehicle_type', sa.String(length=32), nullable=True),
    sa.Column('vehicle_color', sa.String(length=32), nullable=True),
    sa.Column('object_label', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('snapshot_url', sa.String(length=512), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('source_client', sa.String(length=128), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('repeat_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('watchlist_hit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_uid')
    )
    op.create_index('ix_events_camera_time', 'detection_events', ['camera_id', 'detected_at'], unique=False)
    op.create_index('ix_events_detected_at', 'detection_events', ['detected_at'], unique=False)
    op.create_index('ix_events_identifier_time', 'detection_events', ['identifier_normalized', 'detected_at'], unique=False)
    op.create_index('ix_events_type_time', 'detection_events', ['event_type', 'detected_at'], unique=False)
    op.create_table('watchlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('VEHICLE', 'PERSON', name='entitytype', native_enum=False, length=24), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('identifier_normalized', sa.String(length=64), nullable=False),
    sa.Column('category', sa.Enum('STOLEN_VEHICLE', 'BLACKLISTED_VEHICLE', 'WANTED_PERSON', 'MISSING_PERSON', 'SUSPICIOUS', name='watchlistcategory', native_enum=False, length=24), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('case_reference', sa.String(length=64), nullable=True),
    sa.Column('source_agency', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_until', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'identifier_normalized', name='uq_watchlist_identity')
    )
    op.create_index('ix_watchlist_active', 'watchlist_entries', ['is_active'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('watchlist_entry_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(length=32), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('identifier_normalized', sa.String(length=64), nullable=False),
    sa.Column('match_type', sa.Enum('EXACT', 'FUZZY', name='matchtype', native_enum=False, length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, length=24), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'RESOLVED', 'FALSE_POSITIVE', name='alertstatus', native_enum=False, length=24), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('triggered_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_hit_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['detection_events.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['watchlist_entry_id'], ['watchlist_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_identifier', 'alerts', ['identifier_normalized'], unique=False)
    op.create_index('ix_alerts_status_time', 'alerts', ['status', 'triggered_at'], unique=False)
    op.create_index('ix_alerts_watch_cam_time', 'alerts', ['watchlist_entry_id', 'camera_id', 'last_hit_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_watch_cam_time', table_name='alerts')
    op.drop_index('ix_alerts_status_time', table_name='alerts')
    op.drop_index('ix_alerts_identifier', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_watchlist_active', table_name='watchlist_entries')
    op.drop_table('watchlist_entries')
    op.drop_index('ix_events_type_time', table_name='detection_events')
    op.drop_index('ix_events_identifier_time', table_name='detection_events')
    op.drop_index('ix_events_detected_at', table_name='detection_events')
    op.drop_index('ix_events_camera_time', table_name='detection_events')
    op.drop_table('detection_events')
    op.drop_table('users')
    op.drop_index('ix_cameras_status', table_name='cameras')
    op.drop_index('ix_cameras_protocol', table_name='cameras')
    op.drop_index('ix_cameras_geo', table_name='cameras')
    op.drop_index('ix_cameras_dept_zone', table_name='cameras')
    op.drop_table('cameras')
    op.drop_table('departments')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('api_clients')
    # ### end Alembic commands ###
