"""dashcam telemetry

Revision ID: c56146b3de58
Revises: 2137c3e61bfd
Create Date: 2026-09-26 10:46:40.481346
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.models.types


revision: str = 'c56146b3de58'
down_revision: str | None = '2137c3e61bfd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_positions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(length=32), nullable=False),
    sa.Column('recorded_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_positions_camera_time', 'camera_positions', ['camera_id', 'recorded_at'], unique=False)
    op.add_column('cameras', sa.Column('speed_kmh', sa.Float(), nullable=True))
    op.add_column('cameras', sa.Column('heading_deg', sa.Float(), nullable=True))
    op.add_column('cameras', sa.Column('location_updated_at', app.models.types.UTCDateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'location_updated_at')
    op.drop_column('cameras', 'heading_deg')
    op.drop_column('cameras', 'speed_kmh')
    op.drop_index('ix_positions_camera_time', table_name='camera_positions')
    op.drop_table('camera_positions')
    # ### end Alembic commands ###
