#!/bin/sh
# Points the Vercel-hosted console at a backend server.
#   scripts/configure-vercel.sh 203-0-113-7.sslip.io
# Writes frontend/vercel.json (HTTP rewrites + security headers) and frontend/.env.vercel
# (WebSocket URL; Vercel cannot proxy WebSockets). Commit both and push: Vercel redeploys.
set -e
cd "$(dirname "$0")/.."
HOST="$1"
case "$HOST" in
  ""|*/*|*:*) echo "usage: $0 <backend-host>   (a bare host name, e.g. 203-0-113-7.sslip.io)"; exit 1 ;;
esac
sed "s/__BACKEND_HOST__/$HOST/g" frontend/vercel.template.json > frontend/vercel.json
printf "# Generated by scripts/configure-vercel.sh (public value, not a secret)\nVITE_WS_URL=wss://%s/api/v1/ws\n" "$HOST" > frontend/.env.vercel
echo "Configured Vercel build for backend https://$HOST"
